"""
Complete database of 27 Nakshatras with Indian & Western star names.
Includes astrological properties and financial characteristics.
"""

NAKSHATRAS = [
    {
        "number": 1,
        "name_sanskrit": "अश्विनी",
        "name_english": "Ashwini",
        "name_hindi": "अश्विनी",
        "star_name_indian": "Ashwini Kumar",
        "star_name_western": "Beta Arietis",
        "common_name_western": "Sheratan",
        "bayer_designation": "β Ari",
        "constellation": "Aries (Mesha)",
        "degree_range_start": 0.0,
        "degree_range_end": 13.333333,
        "ruling_deity": "Ashwini Kumaras (Divine Physicians)",
        "ruling_deity_hindi": "अश्विनी कुमार",
        "ruling_planet": "Ketu (South Node)",
        "ruling_planet_hindi": "केतु",
        "element": "Earth",
        "gana": "Deva (Divine)",
        "nature": "Light, Swift",
        "quality": "Laghu (Light)",
        "symbol": "Horse's Head",
        "yoni": "Horse",
        "characteristics": ["Quick action", "Healing", "Speed", "Initiative", "New beginnings"],
        "positive_traits": ["Swift decisions", "Healing ability", "Pioneering spirit"],
        "negative_traits": ["Impatience", "Recklessness", "Restlessness"],
        "financial_traits": ["Sudden gains", "Quick trades", "Impulsive investments", "Day trading success"],
        "favorable_for": ["NIFTY IT", "NIFTY BANK", "F&O Index"],
        "unfavorable_for": ["Long-term holdings", "Value investing"],
        "lucky_colors": ["Red", "Orange", "Crimson"],
        "lucky_numbers": [1, 7],
        "lucky_days": ["Tuesday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 2,
        "name_sanskrit": "भरणी",
        "name_english": "Bharani",
        "name_hindi": "भरणी",
        "star_name_indian": "Yama Tara",
        "star_name_western": "41 Arietis",
        "common_name_western": "41 Ari",
        "bayer_designation": "41 Ari",
        "constellation": "Aries (Mesha)",
        "degree_range_start": 13.333333,
        "degree_range_end": 26.666666,
        "ruling_deity": "Yama (God of Death/Transformation)",
        "ruling_deity_hindi": "यम",
        "ruling_planet": "Venus (Shukra)",
        "ruling_planet_hindi": "शुक्र",
        "element": "Earth",
        "gana": "Manushya (Human)",
        "nature": "Fierce, Restraint",
        "quality": "Ugra (Fierce)",
        "symbol": "Yoni (Womb)",
        "yoni": "Elephant",
        "characteristics": ["Transformation", "Nurturing", "Preservation", "Discipline"],
        "positive_traits": ["Patient", "Nurturing", "Wealth accumulation"],
        "negative_traits": ["Stubborn", "Controlling", "Jealous"],
        "financial_traits": ["Long-term holdings", "Value investing", "Wealth accumulation", "Conservative approach"],
        "favorable_for": ["NIFTY 50", "NIFTY Pharma", "NIFTY FMCG"],
        "unfavorable_for": ["Speculation", "Quick trades"],
        "lucky_colors": ["Red", "White", "Pink"],
        "lucky_numbers": [2, 9],
        "lucky_days": ["Friday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 3,
        "name_sanskrit": "कृत्तिका",
        "name_english": "Krittika",
        "name_hindi": "कृत्तिका",
        "star_name_indian": "Kartik Tara",
        "star_name_western": "Eta Tauri (Alcyone)",
        "common_name_western": "Alcyone (Pleiades)",
        "bayer_designation": "η Tau",
        "constellation": "Aries/Taurus (Mesha/Vrishabha)",
        "degree_range_start": 26.666666,
        "degree_range_end": 40.0,
        "ruling_deity": "Agni (God of Fire)",
        "ruling_deity_hindi": "अग्नि",
        "ruling_planet": "Sun (Surya)",
        "ruling_planet_hindi": "सूर्य",
        "element": "Fire",
        "gana": "Rakshasa (Demon)",
        "nature": "Sharp, Cutting",
        "quality": "Tikshna (Sharp)",
        "symbol": "Razor, Flame, Knife",
        "yoni": "Sheep",
        "characteristics": ["Purification", "Transformation", "Sharpness", "Power"],
        "positive_traits": ["Strong willpower", "Leadership", "Decisive"],
        "negative_traits": ["Aggressive", "Critical", "Destructive"],
        "financial_traits": ["Aggressive trading", "High risk appetite", "Speculative gains", "Cutting losses quickly"],
        "favorable_for": ["NIFTY Bank", "NIFTY Financial", "F&O Index"],
        "unfavorable_for": ["Conservative investing", "Risk-averse portfolios"],
        "lucky_colors": ["Red", "Gold", "Orange"],
        "lucky_numbers": [3, 6],
        "lucky_days": ["Sunday"],
        "historical_market_tendency": "Volatile",
        "avg_return_percentage": None,
    },
    {
        "number": 4,
        "name_sanskrit": "रोहिणी",
        "name_english": "Rohini",
        "name_hindi": "रोहिणी",
        "star_name_indian": "Rohini Tara",
        "star_name_western": "Alpha Tauri",
        "common_name_western": "Aldebaran",
        "bayer_designation": "α Tau",
        "constellation": "Taurus (Vrishabha)",
        "degree_range_start": 40.0,
        "degree_range_end": 53.333333,
        "ruling_deity": "Brahma (Creator God)",
        "ruling_deity_hindi": "ब्रह्मा",
        "ruling_planet": "Moon (Chandra)",
        "ruling_planet_hindi": "चन्द्र",
        "element": "Earth",
        "gana": "Manushya (Human)",
        "nature": "Fixed, Stable",
        "quality": "Dhruva (Fixed)",
        "symbol": "Chariot, Ox Cart",
        "yoni": "Serpent",
        "characteristics": ["Growth", "Fertility", "Abundance", "Beauty"],
        "positive_traits": ["Attractive", "Artistic", "Prosperous"],
        "negative_traits": ["Materialistic", "Possessive", "Indulgent"],
        "financial_traits": ["Wealth accumulation", "Real estate gains", "Luxury investments", "Steady growth"],
        "favorable_for": ["NIFTY 50", "NIFTY Realty", "NIFTY FMCG"],
        "unfavorable_for": ["High-risk speculation", "Short selling"],
        "lucky_colors": ["White", "Cream", "Pink"],
        "lucky_numbers": [2, 4],
        "lucky_days": ["Monday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 5,
        "name_sanskrit": "मृगशिरा",
        "name_english": "Mrigashira",
        "name_hindi": "मृगशिरा",
        "star_name_indian": "Mrig Tara",
        "star_name_western": "Lambda Orionis",
        "common_name_western": "Meissa",
        "bayer_designation": "λ Ori",
        "constellation": "Taurus/Gemini (Vrishabha/Mithuna)",
        "degree_range_start": 53.333333,
        "degree_range_end": 66.666666,
        "ruling_deity": "Soma (Moon God)",
        "ruling_deity_hindi": "सोम",
        "ruling_planet": "Mars (Mangal)",
        "ruling_planet_hindi": "मंगल",
        "element": "Earth",
        "gana": "Deva (Divine)",
        "nature": "Soft, Tender",
        "quality": "Mridu (Soft)",
        "symbol": "Deer's Head",
        "yoni": "Serpent",
        "characteristics": ["Searching", "Curiosity", "Exploration", "Research"],
        "positive_traits": ["Curious", "Intellectual", "Sociable"],
        "negative_traits": ["Fickle", "Restless", "Indecisive"],
        "financial_traits": ["Research-based investing", "Sector rotation", "Multiple portfolios", "Active management"],
        "favorable_for": ["NIFTY IT", "NIFTY Auto", "NIFTY Metal"],
        "unfavorable_for": ["Single stock bets", "Concentrated portfolios"],
        "lucky_colors": ["Silver", "Grey", "White"],
        "lucky_numbers": [5, 9],
        "lucky_days": ["Tuesday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 6,
        "name_sanskrit": "आर्द्रा",
        "name_english": "Ardra",
        "name_hindi": "आर्द्रा",
        "star_name_indian": "Rudra Tara",
        "star_name_western": "Alpha Orionis",
        "common_name_western": "Betelgeuse",
        "bayer_designation": "α Ori",
        "constellation": "Gemini (Mithuna)",
        "degree_range_start": 66.666666,
        "degree_range_end": 80.0,
        "ruling_deity": "Rudra (Storm God)",
        "ruling_deity_hindi": "रुद्र",
        "ruling_planet": "Rahu (North Node)",
        "ruling_planet_hindi": "राहु",
        "element": "Water",
        "gana": "Manushya (Human)",
        "nature": "Sharp, Fierce",
        "quality": "Tikshna (Sharp)",
        "symbol": "Teardrop, Diamond",
        "yoni": "Dog",
        "characteristics": ["Destruction", "Renewal", "Storms", "Emotional intensity"],
        "positive_traits": ["Intellectually brilliant", "Research-oriented", "Transformative"],
        "negative_traits": ["Emotional turmoil", "Destructive", "Ungrateful"],
        "financial_traits": ["Market crashes", "Volatile swings", "Contrarian plays", "Bearish tendencies"],
        "favorable_for": ["NIFTY Bank", "NIFTY Metal", "F&O Index"],
        "unfavorable_for": ["New investments", "Long positions", "IPOs"],
        "lucky_colors": ["Green", "Dark Green"],
        "lucky_numbers": [4, 8],
        "lucky_days": ["Wednesday"],
        "historical_market_tendency": "Bearish",
        "avg_return_percentage": None,
    },
    {
        "number": 7,
        "name_sanskrit": "पुनर्वसु",
        "name_english": "Punarvasu",
        "name_hindi": "पुनर्वसु",
        "star_name_indian": "Aditi Tara",
        "star_name_western": "Beta Geminorum",
        "common_name_western": "Pollux",
        "bayer_designation": "β Gem",
        "constellation": "Gemini/Cancer (Mithuna/Karka)",
        "degree_range_start": 80.0,
        "degree_range_end": 93.333333,
        "ruling_deity": "Aditi (Mother of Gods)",
        "ruling_deity_hindi": "अदिति",
        "ruling_planet": "Jupiter (Guru)",
        "ruling_planet_hindi": "गुरु",
        "element": "Air",
        "gana": "Deva (Divine)",
        "nature": "Movable",
        "quality": "Chara (Movable)",
        "symbol": "Bow, Quiver of Arrows",
        "yoni": "Cat",
        "characteristics": ["Renewal", "Return", "Restoration", "Abundance"],
        "positive_traits": ["Generous", "Optimistic", "Wise"],
        "negative_traits": ["Indecisive", "Over-optimistic", "Lazy"],
        "financial_traits": ["Recovery plays", "Bounce-back stocks", "Value recovery", "Portfolio rebalancing"],
        "favorable_for": ["NIFTY 50", "NIFTY Pharma", "NIFTY FMCG"],
        "unfavorable_for": ["Aggressive speculation", "Momentum trading"],
        "lucky_colors": ["Yellow", "Gold", "White"],
        "lucky_numbers": [3, 7],
        "lucky_days": ["Thursday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 8,
        "name_sanskrit": "पुष्य",
        "name_english": "Pushya",
        "name_hindi": "पुष्य",
        "star_name_indian": "Brihaspati Tara",
        "star_name_western": "Delta Cancri",
        "common_name_western": "Asellus Australis",
        "bayer_designation": "δ Cnc",
        "constellation": "Cancer (Karka)",
        "degree_range_start": 93.333333,
        "degree_range_end": 106.666666,
        "ruling_deity": "Brihaspati (Jupiter/Guru)",
        "ruling_deity_hindi": "बृहस्पति",
        "ruling_planet": "Saturn (Shani)",
        "ruling_planet_hindi": "शनि",
        "element": "Water",
        "gana": "Deva (Divine)",
        "nature": "Light, Auspicious",
        "quality": "Laghu (Light)",
        "symbol": "Lotus, Circle, Arrow",
        "yoni": "Sheep",
        "characteristics": ["Nourishment", "Prosperity", "Most auspicious", "Wealth"],
        "positive_traits": ["Generous", "Spiritual", "Wealthy"],
        "negative_traits": ["Over-cautious", "Rigid", "Stubborn"],
        "financial_traits": ["Most auspicious for investments", "Steady wealth", "Safe havens", "Gold investments"],
        "favorable_for": ["NIFTY 50", "NIFTY Bank", "NIFTY IT"],
        "unfavorable_for": ["Nothing - most auspicious nakshatra"],
        "lucky_colors": ["Yellow", "Orange", "Saffron"],
        "lucky_numbers": [8, 3],
        "lucky_days": ["Thursday", "Saturday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 9,
        "name_sanskrit": "आश्लेषा",
        "name_english": "Ashlesha",
        "name_hindi": "आश्लेषा",
        "star_name_indian": "Naga Tara",
        "star_name_western": "Epsilon Hydrae",
        "common_name_western": "Ashlesha",
        "bayer_designation": "ε Hya",
        "constellation": "Cancer (Karka)",
        "degree_range_start": 106.666666,
        "degree_range_end": 120.0,
        "ruling_deity": "Sarpa/Naga (Serpent God)",
        "ruling_deity_hindi": "सर्प/नाग",
        "ruling_planet": "Mercury (Budh)",
        "ruling_planet_hindi": "बुध",
        "element": "Water",
        "gana": "Rakshasa (Demon)",
        "nature": "Sharp, Dreadful",
        "quality": "Tikshna (Sharp)",
        "symbol": "Coiled Serpent",
        "yoni": "Cat",
        "characteristics": ["Cunning", "Wisdom", "Mystical", "Hidden knowledge"],
        "positive_traits": ["Clever", "Mystical insight", "Penetrating mind"],
        "negative_traits": ["Deceptive", "Manipulative", "Secretive"],
        "financial_traits": ["Insider knowledge", "Hidden opportunities", "Cunning trades", "Complex instruments"],
        "favorable_for": ["NIFTY Bank", "NIFTY Financial", "NIFTY IT"],
        "unfavorable_for": ["Transparent investments", "Simple buy-hold"],
        "lucky_colors": ["Black", "Dark Red", "Mercury colors"],
        "lucky_numbers": [5, 4],
        "lucky_days": ["Wednesday"],
        "historical_market_tendency": "Bearish",
        "avg_return_percentage": None,
    },
    {
        "number": 10,
        "name_sanskrit": "मघा",
        "name_english": "Magha",
        "name_hindi": "मघा",
        "star_name_indian": "Pitr Tara",
        "star_name_western": "Alpha Leonis",
        "common_name_western": "Regulus",
        "bayer_designation": "α Leo",
        "constellation": "Leo (Simha)",
        "degree_range_start": 120.0,
        "degree_range_end": 133.333333,
        "ruling_deity": "Pitrs (Ancestors)",
        "ruling_deity_hindi": "पितृ",
        "ruling_planet": "Ketu (South Node)",
        "ruling_planet_hindi": "केतु",
        "element": "Fire",
        "gana": "Rakshasa (Demon)",
        "nature": "Fierce, Severe",
        "quality": "Ugra (Fierce)",
        "symbol": "Royal Throne, Palanquin",
        "yoni": "Rat",
        "characteristics": ["Authority", "Power", "Royalty", "Ancestral wealth"],
        "positive_traits": ["Authoritative", "Generous", "Noble"],
        "negative_traits": ["Arrogant", "Domineering", "Harsh"],
        "financial_traits": ["Large-cap stocks", "Blue-chip", "Government bonds", "Institutional investing"],
        "favorable_for": ["NIFTY 50", "NIFTY PSE", "NIFTY Infra"],
        "unfavorable_for": ["Small-cap speculation", "Penny stocks"],
        "lucky_colors": ["Ivory", "Cream", "Gold"],
        "lucky_numbers": [1, 7],
        "lucky_days": ["Sunday", "Tuesday"],
        "historical_market_tendency": "Volatile",
        "avg_return_percentage": None,
    },
    {
        "number": 11,
        "name_sanskrit": "पूर्वा फाल्गुनी",
        "name_english": "Purva Phalguni",
        "name_hindi": "पूर्वा फाल्गुनी",
        "star_name_indian": "Bhaga Tara",
        "star_name_western": "Delta Leonis",
        "common_name_western": "Zosma",
        "bayer_designation": "δ Leo",
        "constellation": "Leo (Simha)",
        "degree_range_start": 133.333333,
        "degree_range_end": 146.666666,
        "ruling_deity": "Bhaga (God of Fortune)",
        "ruling_deity_hindi": "भग",
        "ruling_planet": "Venus (Shukra)",
        "ruling_planet_hindi": "शुक्र",
        "element": "Fire",
        "gana": "Manushya (Human)",
        "nature": "Fierce",
        "quality": "Ugra (Fierce)",
        "symbol": "Front legs of bed, Hammock",
        "yoni": "Rat",
        "characteristics": ["Enjoyment", "Luxury", "Creativity", "Romance"],
        "positive_traits": ["Creative", "Generous", "Loving"],
        "negative_traits": ["Vanity", "Laziness", "Over-indulgence"],
        "financial_traits": ["Luxury stocks", "Entertainment sector", "Consumer goods", "Art investments"],
        "favorable_for": ["NIFTY FMCG", "NIFTY Auto", "NIFTY Media"],
        "unfavorable_for": ["Industrial stocks", "Defensive sectors"],
        "lucky_colors": ["Light Brown", "Cream", "Pink"],
        "lucky_numbers": [6, 9],
        "lucky_days": ["Friday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 12,
        "name_sanskrit": "उत्तरा फाल्गुनी",
        "name_english": "Uttara Phalguni",
        "name_hindi": "उत्तरा फाल्गुनी",
        "star_name_indian": "Aryaman Tara",
        "star_name_western": "Beta Leonis",
        "common_name_western": "Denebola",
        "bayer_designation": "β Leo",
        "constellation": "Leo/Virgo (Simha/Kanya)",
        "degree_range_start": 146.666666,
        "degree_range_end": 160.0,
        "ruling_deity": "Aryaman (God of Patronage)",
        "ruling_deity_hindi": "अर्यमन",
        "ruling_planet": "Sun (Surya)",
        "ruling_planet_hindi": "सूर्य",
        "element": "Fire",
        "gana": "Manushya (Human)",
        "nature": "Fixed, Stable",
        "quality": "Dhruva (Fixed)",
        "symbol": "Back legs of bed",
        "yoni": "Cow",
        "characteristics": ["Partnerships", "Contracts", "Prosperity", "Helping"],
        "positive_traits": ["Friendly", "Helpful", "Prosperous"],
        "negative_traits": ["Stubborn", "Egotistical", "Restless"],
        "financial_traits": ["Partnership deals", "Contracts", "Mergers", "Joint ventures"],
        "favorable_for": ["NIFTY Financial", "NIFTY Bank", "NIFTY 50"],
        "unfavorable_for": ["Solo ventures", "Risky bets"],
        "lucky_colors": ["Bright Blue", "Orange", "Gold"],
        "lucky_numbers": [1, 6],
        "lucky_days": ["Sunday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 13,
        "name_sanskrit": "हस्त",
        "name_english": "Hasta",
        "name_hindi": "हस्त",
        "star_name_indian": "Savitar Tara",
        "star_name_western": "Delta Corvi",
        "common_name_western": "Algorab",
        "bayer_designation": "δ Crv",
        "constellation": "Virgo (Kanya)",
        "degree_range_start": 160.0,
        "degree_range_end": 173.333333,
        "ruling_deity": "Savitar (Sun God, Creative power)",
        "ruling_deity_hindi": "सवितर",
        "ruling_planet": "Moon (Chandra)",
        "ruling_planet_hindi": "चन्द्र",
        "element": "Fire",
        "gana": "Deva (Divine)",
        "nature": "Light, Swift",
        "quality": "Laghu (Light)",
        "symbol": "Open Hand, Fist",
        "yoni": "Buffalo",
        "characteristics": ["Skill", "Craftsmanship", "Resourcefulness", "Dexterity"],
        "positive_traits": ["Skillful", "Clever", "Resourceful"],
        "negative_traits": ["Cunning", "Manipulative", "Unscrupulous"],
        "financial_traits": ["Skillful trading", "Technical analysis", "Chart patterns", "Precise entries"],
        "favorable_for": ["NIFTY IT", "NIFTY Bank", "F&O Index"],
        "unfavorable_for": ["Emotional trading", "Random entries"],
        "lucky_colors": ["Green", "Pearl White"],
        "lucky_numbers": [2, 5],
        "lucky_days": ["Monday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 14,
        "name_sanskrit": "चित्रा",
        "name_english": "Chitra",
        "name_hindi": "चित्रा",
        "star_name_indian": "Tvashtar Tara",
        "star_name_western": "Alpha Virginis",
        "common_name_western": "Spica",
        "bayer_designation": "α Vir",
        "constellation": "Virgo/Libra (Kanya/Tula)",
        "degree_range_start": 173.333333,
        "degree_range_end": 186.666666,
        "ruling_deity": "Tvashtar (Celestial Architect)",
        "ruling_deity_hindi": "त्वष्टा",
        "ruling_planet": "Mars (Mangal)",
        "ruling_planet_hindi": "मंगल",
        "element": "Fire",
        "gana": "Rakshasa (Demon)",
        "nature": "Soft, Gentle",
        "quality": "Mridu (Soft)",
        "symbol": "Bright Jewel, Pearl",
        "yoni": "Tiger",
        "characteristics": ["Brilliance", "Creativity", "Illusion", "Beauty"],
        "positive_traits": ["Creative", "Elegant", "Visionary"],
        "negative_traits": ["Superficial", "Vain", "Critical"],
        "financial_traits": ["Creative industries", "Tech stocks", "Glamour sectors", "IPOs"],
        "favorable_for": ["NIFTY IT", "NIFTY Media", "NIFTY FMCG"],
        "unfavorable_for": ["Traditional sectors", "Boring stocks"],
        "lucky_colors": ["Black", "Dark Blue", "Multi-color"],
        "lucky_numbers": [5, 9],
        "lucky_days": ["Tuesday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 15,
        "name_sanskrit": "स्वाति",
        "name_english": "Swati",
        "name_hindi": "स्वाति",
        "star_name_indian": "Vayu Tara",
        "star_name_western": "Alpha Bootis",
        "common_name_western": "Arcturus",
        "bayer_designation": "α Boo",
        "constellation": "Libra (Tula)",
        "degree_range_start": 186.666666,
        "degree_range_end": 200.0,
        "ruling_deity": "Vayu (Wind God)",
        "ruling_deity_hindi": "वायु",
        "ruling_planet": "Rahu (North Node)",
        "ruling_planet_hindi": "राहु",
        "element": "Air",
        "gana": "Deva (Divine)",
        "nature": "Movable",
        "quality": "Chara (Movable)",
        "symbol": "Young Shoot, Coral",
        "yoni": "Buffalo",
        "characteristics": ["Independence", "Movement", "Flexibility", "Trade"],
        "positive_traits": ["Independent", "Diplomatic", "Flexible"],
        "negative_traits": ["Restless", "Indecisive", "Scattered"],
        "financial_traits": ["Trade-oriented", "Import-export", "Currency markets", "Wind-driven sectors"],
        "favorable_for": ["NIFTY IT", "NIFTY Energy", "NIFTY Metal"],
        "unfavorable_for": ["Fixed deposits", "Conservative bonds"],
        "lucky_colors": ["Black", "Dark Blue"],
        "lucky_numbers": [4, 8],
        "lucky_days": ["Saturday"],
        "historical_market_tendency": "Volatile",
        "avg_return_percentage": None,
    },
    {
        "number": 16,
        "name_sanskrit": "विशाखा",
        "name_english": "Vishakha",
        "name_hindi": "विशाखा",
        "star_name_indian": "Indragni Tara",
        "star_name_western": "Alpha Librae",
        "common_name_western": "Zubenelgenubi",
        "bayer_designation": "α Lib",
        "constellation": "Libra/Scorpio (Tula/Vrischika)",
        "degree_range_start": 200.0,
        "degree_range_end": 213.333333,
        "ruling_deity": "Indra-Agni (King of Gods & Fire)",
        "ruling_deity_hindi": "इंद्राग्नि",
        "ruling_planet": "Jupiter (Guru)",
        "ruling_planet_hindi": "गुरु",
        "element": "Fire",
        "gana": "Rakshasa (Demon)",
        "nature": "Mixed",
        "quality": "Mishra (Mixed)",
        "symbol": "Triumphal Arch, Potter's Wheel",
        "yoni": "Tiger",
        "characteristics": ["Determination", "Goal-oriented", "Hard work", "Achievement"],
        "positive_traits": ["Determined", "Focused", "Ambitious"],
        "negative_traits": ["Jealous", "Hypocritical", "Argumentative"],
        "financial_traits": ["Goal-oriented investing", "Sector bets", "Thematic funds", "Target-based trading"],
        "favorable_for": ["NIFTY Pharma", "NIFTY Energy", "NIFTY Infra"],
        "unfavorable_for": ["Passive investing", "Index funds"],
        "lucky_colors": ["Gold", "Yellow", "Red"],
        "lucky_numbers": [3, 7],
        "lucky_days": ["Thursday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 17,
        "name_sanskrit": "अनुराधा",
        "name_english": "Anuradha",
        "name_hindi": "अनुराधा",
        "star_name_indian": "Mitra Tara",
        "star_name_western": "Delta Scorpii",
        "common_name_western": "Dschubba",
        "bayer_designation": "δ Sco",
        "constellation": "Scorpio (Vrischika)",
        "degree_range_start": 213.333333,
        "degree_range_end": 226.666666,
        "ruling_deity": "Mitra (God of Friendship)",
        "ruling_deity_hindi": "मित्र",
        "ruling_planet": "Saturn (Shani)",
        "ruling_planet_hindi": "शनि",
        "element": "Water",
        "gana": "Deva (Divine)",
        "nature": "Soft, Gentle",
        "quality": "Mridu (Soft)",
        "symbol": "Lotus, Triumphal Archway",
        "yoni": "Hare",
        "characteristics": ["Friendship", "Cooperation", "Devotion", "Success abroad"],
        "positive_traits": ["Loyal", "Cooperative", "Hardworking"],
        "negative_traits": ["Jealous", "Secretive", "Controlling"],
        "financial_traits": ["Cooperative investments", "Group investing", "International markets", "Steady returns"],
        "favorable_for": ["NIFTY IT", "NIFTY 50", "NIFTY Bank"],
        "unfavorable_for": ["Solo risky bets", "Day trading"],
        "lucky_colors": ["Red", "Maroon"],
        "lucky_numbers": [8, 4],
        "lucky_days": ["Saturday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 18,
        "name_sanskrit": "ज्येष्ठा",
        "name_english": "Jyeshtha",
        "name_hindi": "ज्येष्ठा",
        "star_name_indian": "Indra Tara",
        "star_name_western": "Alpha Scorpii",
        "common_name_western": "Antares",
        "bayer_designation": "α Sco",
        "constellation": "Scorpio (Vrischika)",
        "degree_range_start": 226.666666,
        "degree_range_end": 240.0,
        "ruling_deity": "Indra (King of Gods)",
        "ruling_deity_hindi": "इन्द्र",
        "ruling_planet": "Mercury (Budh)",
        "ruling_planet_hindi": "बुध",
        "element": "Air",
        "gana": "Rakshasa (Demon)",
        "nature": "Sharp, Dreadful",
        "quality": "Tikshna (Sharp)",
        "symbol": "Circular Amulet, Earring",
        "yoni": "Hare",
        "characteristics": ["Seniority", "Protection", "Authority", "Arrogance"],
        "positive_traits": ["Protective", "Courageous", "Generous"],
        "negative_traits": ["Arrogant", "Vindictive", "Secretive"],
        "financial_traits": ["Large-cap dominance", "Market leadership", "Power plays", "Hostile takeovers"],
        "favorable_for": ["NIFTY 50", "NIFTY Energy", "NIFTY PSE"],
        "unfavorable_for": ["Small-cap", "Micro-cap", "Startups"],
        "lucky_colors": ["Cream", "Light Blue"],
        "lucky_numbers": [5, 3],
        "lucky_days": ["Wednesday"],
        "historical_market_tendency": "Volatile",
        "avg_return_percentage": None,
    },
    {
        "number": 19,
        "name_sanskrit": "मूल",
        "name_english": "Mula",
        "name_hindi": "मूल",
        "star_name_indian": "Nirriti Tara",
        "star_name_western": "Epsilon Scorpii",
        "common_name_western": "Larawag",
        "bayer_designation": "ε Sco",
        "constellation": "Sagittarius (Dhanu)",
        "degree_range_start": 240.0,
        "degree_range_end": 253.333333,
        "ruling_deity": "Nirriti (Goddess of Destruction)",
        "ruling_deity_hindi": "निऋति",
        "ruling_planet": "Ketu (South Node)",
        "ruling_planet_hindi": "केतु",
        "element": "Air",
        "gana": "Rakshasa (Demon)",
        "nature": "Sharp, Dreadful",
        "quality": "Tikshna (Sharp)",
        "symbol": "Bunch of Roots, Tail of Lion",
        "yoni": "Dog",
        "characteristics": ["Destruction", "Root cause", "Uprooting", "Transformation"],
        "positive_traits": ["Investigative", "Philosophical", "Ambitious"],
        "negative_traits": ["Destructive", "Arrogant", "Self-destructive"],
        "financial_traits": ["Market crashes", "Root cause analysis", "Deep value", "Distressed assets"],
        "favorable_for": ["NIFTY Metal", "NIFTY Realty", "NIFTY Bank"],
        "unfavorable_for": ["New investments", "IPOs", "Momentum stocks"],
        "lucky_colors": ["Brown", "Yellow", "Gold"],
        "lucky_numbers": [7, 1],
        "lucky_days": ["Tuesday"],
        "historical_market_tendency": "Bearish",
        "avg_return_percentage": None,
    },
    {
        "number": 20,
        "name_sanskrit": "पूर्वाषाढ़ा",
        "name_english": "Purva Ashadha",
        "name_hindi": "पूर्वाषाढ़ा",
        "star_name_indian": "Apah Tara",
        "star_name_western": "Delta Sagittarii",
        "common_name_western": "Kaus Media",
        "bayer_designation": "δ Sgr",
        "constellation": "Sagittarius (Dhanu)",
        "degree_range_start": 253.333333,
        "degree_range_end": 266.666666,
        "ruling_deity": "Apah (Water God)",
        "ruling_deity_hindi": "अपः",
        "ruling_planet": "Venus (Shukra)",
        "ruling_planet_hindi": "शुक्र",
        "element": "Water",
        "gana": "Manushya (Human)",
        "nature": "Fierce",
        "quality": "Ugra (Fierce)",
        "symbol": "Elephant Tusk, Fan",
        "yoni": "Monkey",
        "characteristics": ["Invincibility", "Declaration", "Purification", "Renewal"],
        "positive_traits": ["Influential", "Proud", "Independent"],
        "negative_traits": ["Over-confident", "Rigid", "Obstinate"],
        "financial_traits": ["Momentum investing", "Growth stocks", "Aggressive positions", "Sector leaders"],
        "favorable_for": ["NIFTY IT", "NIFTY Auto", "NIFTY Pharma"],
        "unfavorable_for": ["Value stocks", "Defensive plays"],
        "lucky_colors": ["Off-White", "Cream"],
        "lucky_numbers": [6, 9],
        "lucky_days": ["Friday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 21,
        "name_sanskrit": "उत्तराषाढ़ा",
        "name_english": "Uttara Ashadha",
        "name_hindi": "उत्तराषाढ़ा",
        "star_name_indian": "Vishvedeva Tara",
        "star_name_western": "Sigma Sagittarii",
        "common_name_western": "Nunki",
        "bayer_designation": "σ Sgr",
        "constellation": "Sagittarius/Capricorn (Dhanu/Makara)",
        "degree_range_start": 266.666666,
        "degree_range_end": 280.0,
        "ruling_deity": "Vishvadevas (Universal Gods)",
        "ruling_deity_hindi": "विश्वदेव",
        "ruling_planet": "Sun (Surya)",
        "ruling_planet_hindi": "सूर्य",
        "element": "Air",
        "gana": "Manushya (Human)",
        "nature": "Fixed, Stable",
        "quality": "Dhruva (Fixed)",
        "symbol": "Elephant Tusk, Small Bed",
        "yoni": "Mongoose",
        "characteristics": ["Final victory", "Penetration", "Leadership", "Endurance"],
        "positive_traits": ["Patient", "Righteous", "Leader"],
        "negative_traits": ["Lonely", "Rigid", "Over-ambitious"],
        "financial_traits": ["Long-term winners", "Blue-chip", "Index funds", "Pension funds"],
        "favorable_for": ["NIFTY 50", "NIFTY Bank", "NIFTY Financial"],
        "unfavorable_for": ["Quick trades", "Penny stocks"],
        "lucky_colors": ["Deep Blue", "Copper"],
        "lucky_numbers": [1, 3],
        "lucky_days": ["Sunday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 22,
        "name_sanskrit": "श्रवण",
        "name_english": "Shravana",
        "name_hindi": "श्रवण",
        "star_name_indian": "Vishnu Tara",
        "star_name_western": "Alpha Aquilae",
        "common_name_western": "Altair",
        "bayer_designation": "α Aql",
        "constellation": "Capricorn (Makara)",
        "degree_range_start": 280.0,
        "degree_range_end": 293.333333,
        "ruling_deity": "Vishnu (Preserver God)",
        "ruling_deity_hindi": "विष्णु",
        "ruling_planet": "Moon (Chandra)",
        "ruling_planet_hindi": "चन्द्र",
        "element": "Air",
        "gana": "Deva (Divine)",
        "nature": "Movable",
        "quality": "Chara (Movable)",
        "symbol": "Ear, Three Footprints",
        "yoni": "Monkey",
        "characteristics": ["Learning", "Listening", "Knowledge", "Connection"],
        "positive_traits": ["Knowledgeable", "Persevering", "Charitable"],
        "negative_traits": ["Overly sensitive", "Gossiper", "Rigid views"],
        "financial_traits": ["Knowledge-based investing", "Education sector", "Media stocks", "Listening to experts"],
        "favorable_for": ["NIFTY IT", "NIFTY Media", "NIFTY Pharma"],
        "unfavorable_for": ["Impulsive trades", "Tip-based trading"],
        "lucky_colors": ["Light Blue", "White"],
        "lucky_numbers": [2, 7],
        "lucky_days": ["Monday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 23,
        "name_sanskrit": "धनिष्ठा",
        "name_english": "Dhanishta",
        "name_hindi": "धनिष्ठा",
        "star_name_indian": "Vasu Tara",
        "star_name_western": "Beta Delphini",
        "common_name_western": "Rotanev",
        "bayer_designation": "β Del",
        "constellation": "Capricorn/Aquarius (Makara/Kumbha)",
        "degree_range_start": 293.333333,
        "degree_range_end": 306.666666,
        "ruling_deity": "Vasus (Gods of Abundance)",
        "ruling_deity_hindi": "वसु",
        "ruling_planet": "Mars (Mangal)",
        "ruling_planet_hindi": "मंगल",
        "element": "Ether",
        "gana": "Rakshasa (Demon)",
        "nature": "Movable",
        "quality": "Chara (Movable)",
        "symbol": "Drum (Mridanga)",
        "yoni": "Lion",
        "characteristics": ["Wealth", "Prosperity", "Fame", "Music"],
        "positive_traits": ["Wealthy", "Talented", "Charitable"],
        "negative_traits": ["Greedy", "Aggressive", "Inconsiderate"],
        "financial_traits": ["Wealth creation", "Aggressive growth", "Royal stocks", "Market beating returns"],
        "favorable_for": ["NIFTY Bank", "NIFTY Realty", "NIFTY Metal"],
        "unfavorable_for": ["Conservative bonds", "Fixed deposits"],
        "lucky_colors": ["Silver", "Blue-Grey"],
        "lucky_numbers": [9, 5],
        "lucky_days": ["Tuesday"],
        "historical_market_tendency": "Bullish",
        "avg_return_percentage": None,
    },
    {
        "number": 24,
        "name_sanskrit": "शतभिषा",
        "name_english": "Shatabhisha",
        "name_hindi": "शतभिषा",
        "star_name_indian": "Varuna Tara",
        "star_name_western": "Lambda Aquarii",
        "common_name_western": "Hydor",
        "bayer_designation": "λ Aqr",
        "constellation": "Aquarius (Kumbha)",
        "degree_range_start": 306.666666,
        "degree_range_end": 320.0,
        "ruling_deity": "Varuna (God of Cosmic Waters)",
        "ruling_deity_hindi": "वरुण",
        "ruling_planet": "Rahu (North Node)",
        "ruling_planet_hindi": "राहु",
        "element": "Ether",
        "gana": "Rakshasa (Demon)",
        "nature": "Movable",
        "quality": "Chara (Movable)",
        "symbol": "Empty Circle, 100 Flowers",
        "yoni": "Horse",
        "characteristics": ["Healing", "Mysticism", "Concealment", "Vast knowledge"],
        "positive_traits": ["Independent", "Innovative", "Healing"],
        "negative_traits": ["Secretive", "Lonely", "Eccentric"],
        "financial_traits": ["Pharma sector", "Healthcare", "Innovative tech", "Unconventional investments"],
        "favorable_for": ["NIFTY Pharma", "NIFTY IT", "NIFTY Bank"],
        "unfavorable_for": ["Traditional banking", "Old economy stocks"],
        "lucky_colors": ["Dark Blue", "Aqua", "Teal"],
        "lucky_numbers": [4, 8],
        "lucky_days": ["Saturday"],
        "historical_market_tendency": "Volatile",
        "avg_return_percentage": None,
    },
    {
        "number": 25,
        "name_sanskrit": "पूर्वा भाद्रपदा",
        "name_english": "Purva Bhadrapada",
        "name_hindi": "पूर्वा भाद्रपदा",
        "star_name_indian": "Ajaikapad Tara",
        "star_name_western": "Alpha Pegasi",
        "common_name_western": "Markab",
        "bayer_designation": "α Peg",
        "constellation": "Aquarius/Pisces (Kumbha/Meena)",
        "degree_range_start": 320.0,
        "degree_range_end": 333.333333,
        "ruling_deity": "Ajaikapada (One-footed Goat)",
        "ruling_deity_hindi": "अजैकपाद",
        "ruling_planet": "Jupiter (Guru)",
        "ruling_planet_hindi": "गुरु",
        "element": "Ether",
        "gana": "Manushya (Human)",
        "nature": "Fierce, Cruel",
        "quality": "Ugra (Fierce)",
        "symbol": "Sword, Two front legs of funeral cot",
        "yoni": "Lion",
        "characteristics": ["Purification by fire", "Penance", "Transformation"],
        "positive_traits": ["Spiritual", "Philosophical", "Self-sacrificing"],
        "negative_traits": ["Anxious", "Cynical", "Unstable"],
        "financial_traits": ["Transformative events", "Market corrections", "Restructuring", "Deep analysis"],
        "favorable_for": ["NIFTY 50", "NIFTY Bank", "NIFTY FMCG"],
        "unfavorable_for": ["Passive investing", "Auto-pilot portfolios"],
        "lucky_colors": ["Silver", "Yellow"],
        "lucky_numbers": [3, 7],
        "lucky_days": ["Thursday"],
        "historical_market_tendency": "Bearish",
        "avg_return_percentage": None,
    },
    {
        "number": 26,
        "name_sanskrit": "उत्तरा भाद्रपदा",
        "name_english": "Uttara Bhadrapada",
        "name_hindi": "उत्तरा भाद्रपदा",
        "star_name_indian": "Ahirbudhnya Tara",
        "star_name_western": "Gamma Pegasi",
        "common_name_western": "Algenib",
        "bayer_designation": "γ Peg",
        "constellation": "Pisces (Meena)",
        "degree_range_start": 333.333333,
        "degree_range_end": 346.666666,
        "ruling_deity": "Ahirbudhnya (Serpent of the Depths)",
        "ruling_deity_hindi": "अहिर्बुध्न्य",
        "ruling_planet": "Saturn (Shani)",
        "ruling_planet_hindi": "शनि",
        "element": "Ether",
        "gana": "Manushya (Human)",
        "nature": "Fixed, Stable",
        "quality": "Dhruva (Fixed)",
        "symbol": "Twins, Back legs of funeral cot",
        "yoni": "Cow",
        "characteristics": ["Deep wisdom", "Wealth", "Mysticism", "Cosmic connection"],
        "positive_traits": ["Wise", "Wealthy", "Charitable"],
        "negative_traits": ["Lazy", "Irresponsible", "Withdrawn"],
        "financial_traits": ["Steady wealth", "Fixed income", "Government securities", "Safe investments"],
        "favorable_for": ["NIFTY FMCG", "NIFTY Pharma", "NIFTY 50"],
        "unfavorable_for": ["High-risk trades", "Leveraged positions"],
        "lucky_colors": ["Purple", "Violet"],
        "lucky_numbers": [8, 6],
        "lucky_days": ["Saturday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
    {
        "number": 27,
        "name_sanskrit": "रेवती",
        "name_english": "Revati",
        "name_hindi": "रेवती",
        "star_name_indian": "Pushan Tara",
        "star_name_western": "Zeta Piscium",
        "common_name_western": "Revati",
        "bayer_designation": "ζ Psc",
        "constellation": "Pisces (Meena)",
        "degree_range_start": 346.666666,
        "degree_range_end": 360.0,
        "ruling_deity": "Pushan (God of Nourishment/Journeys)",
        "ruling_deity_hindi": "पूषन",
        "ruling_planet": "Mercury (Budh)",
        "ruling_planet_hindi": "बुध",
        "element": "Ether",
        "gana": "Deva (Divine)",
        "nature": "Soft, Gentle",
        "quality": "Mridu (Soft)",
        "symbol": "Fish, Drum",
        "yoni": "Elephant",
        "characteristics": ["Completion", "Journey", "Nourishment", "Wealth"],
        "positive_traits": ["Compassionate", "Creative", "Wealthy"],
        "negative_traits": ["Over-sensitive", "Dependent", "Giving too much"],
        "financial_traits": ["Journey completion", "Cycle endings", "Profit booking", "Travel sector"],
        "favorable_for": ["NIFTY Pharma", "NIFTY IT", "NIFTY Financial"],
        "unfavorable_for": ["New positions", "Fresh investments"],
        "lucky_colors": ["Brown", "Light Yellow"],
        "lucky_numbers": [5, 6],
        "lucky_days": ["Wednesday"],
        "historical_market_tendency": "Neutral",
        "avg_return_percentage": None,
    },
]


def get_nakshatra_by_number(number: int) -> dict:
    """Get Nakshatra information by number (1-27)."""
    if 1 <= number <= 27:
        return NAKSHATRAS[number - 1]
    return None


def get_nakshatra_by_name(name: str) -> dict:
    """Get Nakshatra information by English name."""
    for nakshatra in NAKSHATRAS:
        if nakshatra["name_english"].lower() == name.lower():
            return nakshatra
    return None


def get_all_nakshatras() -> list:
    """Get list of all 27 Nakshatras."""
    return NAKSHATRAS


def search_nakshatra_by_star(western_star_name: str) -> dict:
    """Find Nakshatra by Western star name."""
    for nakshatra in NAKSHATRAS:
        if western_star_name.lower() in nakshatra["star_name_western"].lower():
            return nakshatra
    return None


def get_nakshatra_from_longitude(sidereal_longitude: float) -> dict:
    """Get Nakshatra from sidereal Moon longitude (0-360)."""
    nakshatra_span = 360.0 / 27.0
    number = int(sidereal_longitude / nakshatra_span) + 1
    if number > 27:
        number = 27
    return get_nakshatra_by_number(number)


def get_ruling_planet_nakshatras(planet: str) -> list:
    """Get all Nakshatras ruled by a given planet."""
    results = []
    for n in NAKSHATRAS:
        if planet.lower() in n["ruling_planet"].lower():
            results.append(n)
    return results
